name: My Workflow

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        echo "My last name is Shumai"
        echo "My first name is Yevhen"

